### ISSUE TITLE
Throws networking errors

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [achandran/mpv-remote#1]
Errors below. There was a conflict with port 80 which is my Apache server. I changed the port in the code to 8111 but still does not work. Cheers.

michaelzfreeman@michaelzfreeman-G41MT-S2PT
~/ReturnToTheSource/mpv-remote                                                             
$ yarn install
yarn install v1.17.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.17s.
michaelzfreeman@michaelzfreeman-G41MT-S2PT
~/ReturnToTheSource/mpv-remote                                                             
$ node app.js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1260:19)
    at listenInCluster (net.js:1325:12)
    at Server.listen (net.js:1412:7)
    at Function.listen (/home/michaelzfreeman/ReturnToTheSource/mpv-remote/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/michaelzfreeman/ReturnToTheSource/mpv-remote/app.js:32:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1304:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
michaelzfreeman@michaelzfreeman-G41MT-S2PT
~/ReturnToTheSource/mpv-remote                                                             
$ sudo node app.js
[sudo] password for michaelzfreeman: 
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1277:14)
    at listenInCluster (net.js:1325:12)
    at Server.listen (net.js:1412:7)
    at Function.listen (/home/michaelzfreeman/ReturnToTheSource/mpv-remote/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/michaelzfreeman/ReturnToTheSource/mpv-remote/app.js:32:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1304:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
michaelzfreeman@michaelzfreeman-G41MT-S2PT
~/ReturnToTheSource/mpv-remote
$ sudo node app.js
/home/michaelzfreeman/ReturnToTheSource/mpv-remote/app.js:30
  networkInterfaces()['en0'].find(elem => elem.address.startsWith('192')).address;
                            ^

TypeError: Cannot read property 'find' of undefined
    at getNetworkIPAddress (/home/michaelzfreeman/ReturnToTheSource/mpv-remote/app.js:30:29)
    at Server.app.listen (/home/michaelzfreeman/ReturnToTheSource/mpv-remote/app.js:32:64)
    at Object.onceWrapper (events.js:277:13)
    at Server.emit (events.js:189:13)
    at emitListeningNT (net.js:1311:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
michaelzfreeman@michaelzfreeman-G41MT-S2PT
~/ReturnToTheSource/mpv-remote
$

michaelzfreeman@michaelzfreeman-G41MT-S2PT
~
$ nodejs --version
v10.15.2

**Comment by achandran** [comment]
Hello,
I have added an optional command line argument to specify the port.
So for example, to run the server on port 3121, you can run:
`node app.js 3121`
